// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5lX3y-iZ9c2iFQO602YxKB7EfNrkj9D0',
    appId: '1:922836884456:web:13931512316cdce8d0625d',
    messagingSenderId: '922836884456',
    projectId: 'ideal-world-cup-4256f',
    authDomain: 'ideal-world-cup-4256f.firebaseapp.com',
    storageBucket: 'ideal-world-cup-4256f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6YUop1OCrNIuIlI1DY2u8g-iWOHz3eYA',
    appId: '1:922836884456:android:3db9aab92c612d53d0625d',
    messagingSenderId: '922836884456',
    projectId: 'ideal-world-cup-4256f',
    storageBucket: 'ideal-world-cup-4256f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5lX3y-iZ9c2iFQO602YxKB7EfNrkj9D0',
    appId: '1:922836884456:web:1fc1ce2cdc626d99d0625d',
    messagingSenderId: '922836884456',
    projectId: 'ideal-world-cup-4256f',
    authDomain: 'ideal-world-cup-4256f.firebaseapp.com',
    storageBucket: 'ideal-world-cup-4256f.firebasestorage.app',
  );
}
